### ISSUE TITLE
How can I give bonus to workers?

### ISSUE THREAD

**Issue by jnhwkim** [batra-mlp-lab/visdial-amt-chat#2]
Could you briefly explain about giving bonus to AMT workers who have done the job well?

**Comment by abhshkdz** [comment]
The `MTurkConnection`object has a [`grant_bonus`](http://boto.cloudhackers.com/en/latest/ref/mturk.html#boto.mturk.connection.MTurkConnection.grant_bonus) function that takes ids, bonus amount and reason as arguments. You could add this to the [`approve/payWorkers`](https://github.com/batra-mlp-lab/visdial-amt-chat/blob/master/mturk_scripts/approve/payWorkers.py) script near the `approve_assignment()` call. Alternatively, you can also grant bonus manually on the AMT requester website.

**Comment by jnhwkim** [comment]
Then, in database, `bonus` field of `AMTHITS` table is useless?

**Comment by abhshkdz** [comment]
No, that is to keep track of workers you'd want to grant bonus to.

**Comment by jnhwkim** [comment]
@abhshkdz I mean, but for now, there is no script for updating `bonus` field. That's my job to do. I owe you, thanks!

**Comment by jnhwkim** [comment]
@abhshkdz I see. That's my job to do. I owe you, thanks!

**Comment by abhshkdz** [comment]
Yeah, there's no script for updating `bonus` right now. No problem!
