### ISSUE TITLE
Hit URL

### ISSUE THREAD

**Issue by ghost** [batra-mlp-lab/visdial-amt-chat#7]
`url = "https://ENTER_HIT_URL/" # TODO`

For the hit url in `createHits.py`, what would be recommended to do? Should I buy a domain and SSL and set the server up so it's not being run from the local host? Or is it possible to do everything from the local host and just supply `http://127.0.0.1:5000` as the hit URL?

**Comment by abhshkdz** [comment]
Yeah, all external HITs must be hosted on a domain with SSL. You can't launch HITs on Mechanical Turk with the node server running on localhost.
