### ISSUE TITLE
How to make the node js server accessible to others?

### ISSUE THREAD

**Issue by ghost** [batra-mlp-lab/visdial-amt-chat#8]
I can access my node js server at `localhost:5000` or whatever port I use, however, other devices cannot access the server? 

How can they access the server? Would they just type in my Mac's public IP address with the right port? I haven't been able to figure this out, I can only access the server on my localhost. I've managed to use ngrok which works, but it is not a suitable solution for the long term. 

What are some breif steps I can take to setup the server so others can access it? Thank you for your time!

**Comment by abhshkdz** [comment]
Yeah, a public ip + port would make your HITs accessible to others, but to host them on AMT you will need a domain + ssl. More on that [here](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_ExternalQuestionArticle.html).
