### ISSUE TITLE
HTTPS support & trivial question

### ISSUE THREAD

**Issue by tmsausa** [batra-mlp-lab/visdial-amt-chat#9]
Thank you for creating a nice project.
I have two questions. I would appreciate it if you would answer them.
1. ExternalQuestion currently requests a HTTPS webpage. It seems that index.js does not fulfill this requirement. Are you going to support it? If you are not, could I send PullReq which maybe works?

2. I managed to set up this program on an external server following your instructions. I was able to see that this template on workersandbox.mturk.com. However, I could not have two workers have a conversation on it. Do you have any idea to solve this problem? I have little knowledge of node.js and web applications so I may make basic mistakes.

**Comment by abhshkdz** [comment]
1. `index.js` seems to works fine (over https) with an [nginx reverse proxy](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04). Could you be more specific about what it's missing?

2. Do you see any error/debug messages in the browser console, or on the server? Could you paste them here.

**Comment by tmsausa** [comment]
Sorry for the late reply. It was due to my ignorance of node.js and nginx and so forth. Thank you!
Could you tell me the versions of MySQL, nginx, node.js and npm?

**Comment by abhshkdz** [comment]
mysql 14.14
nginx 1.10.3
node 0.10.48
npm 1.3.6

**Comment by tmsausa** [comment]
Thanks!!
